name:                hscp-mb
version:             0.1.0.0
github:              av86743/hscp-mb-final
license:             BSD3
author:              the rightful owner <av86743@users.noreply.github.com>
#maintainer:          "example@example.com"
#copyright:           "2023 Author name here"

homepage:            http://www.github.com/av86743/hscp-mb-final
license-file:        LICENSE

# Metadata used when publishing your package
synopsis:            Call-by-need supercompiler for Haskell Core, by Max Bolingbroke
category:            Language

extra-source-files:
- README.md

description:         See README on GitHub<https://github.com/av86743/hscp-mb-final/README.md>

dependencies:
- base >= 4.7 && < 5

- cpphs
- haskell-src-exts
- prettyclass

- containers
- deepseq
- process
- directory
- filepath
- time

- lattices
- graph-wrapper

- array

ghc-options:
- -Wall
#- -Wcompat
#- -Widentities
#- -Wincomplete-record-updates
#- -Wincomplete-uni-patterns
#- -Wmissing-export-lists
#- -Wmissing-home-modules
#- -Wpartial-fields
#- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hscp-mb-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hscp-mb

tests:
  hscp-mb-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hscp-mb
